version: '3.3'
services:
  cals_acceptance_test:
    image: "cwds/cals:${APP_VERSION}"
    command: bash -c 'yarn run spec-end2end-features'
    volumes:
      - ./reports/:/var/www/cals/reports/
    environment:
      CAPYBARA_APP_HOST: "${CAPYBARA_APP_HOST}"
      USERNAME: "${USERNAME}"
    stdin_open: true
    tty: true
