# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  enabled: true
  host: localhost
  port: 5080

development:
  <<: *default

aws_dev:
  <<: *default
  enabled: false

test:
  <<: *default
  enabled: false

production:
  <<: *default
  enabled: false
