---
http_interactions:
- request:
    method: post
    uri: https://cals-api.preint.cwds.io/rfa-1a-forms
    body:
      encoding: UTF-8
      string: "{}"
    headers:
      Content-type:
      - application/json
  response:
    status:
      code: 201
      message:
    headers:
      date:
      - Tue, 01 Aug 2017 16:20:06 GMT
      content-type:
      - application/json
      content-length:
      - '78'
    body:
      encoding: UTF-8
      string: |-
        {
          "id" : 92,
          "is_initial_application" : false,
          "is_other_type" : false
        }
    http_version:
  recorded_at: Tue, 01 Aug 2017 16:20:04 GMT
recorded_with: VCR 3.0.3
