---
http_interactions:
- request:
    method: post
    uri: https://cals-api.preint.cwds.io/rfa-1a-forms?token=null
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-type:
      - application/json
  response:
    status:
      code: 201
      message: 
    headers:
      content-type:
      - application/json
      date:
      - Mon, 10 Jul 2017 18:14:41 GMT
      content-length:
      - '76'
      connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: |-
        {
          "id" : 7,
          "is_initial_application" : true,
          "is_other_type" : false
        }
    http_version: 
  recorded_at: Mon, 10 Jul 2017 18:14:41 GMT
recorded_with: VCR 3.0.3
