version: '3.3'
services:
  cals:
    # build: .
    command: bash -c "bundle check || bundle install && yarn && bundle exec puma"
    image: cwds/cals:0.62-489
    ports:
      - 3000:3000
    environment:
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
    env_file: docker-compose.env
    links:
      - redis
      - perry
      - cals-api
    tty: true
    stdin_open: true

  redis:
    image: 'redis:3.0'
    ports:
      - 6379:6379

  perry:
    image: cwds/perry:1.6.1_376-RC
    hostname: perry
    ports:
      - 8080:8080
      - 8092:8092
    restart: on-failure
    env_file: docker-compose.env

  cals_db2_data:
    image: cwds/cals_db2_data
    hostname: cals_db2_data

    ports:
      - 50000:50000
    restart: on-failure
    env_file: docker-compose.env

  postgresql_data:
    image: cwds/postgresql_data
    hostname: postgresql_data
    ports:
      - 5432:5432
    restart: on-failure
    env_file: docker-compose.env

  cals-api:
    image: cwds/cals-api:0.6.2_1112-RC
    hostname: cals-api
    depends_on:
      - cals_db2_data
      - postgresql_data
      - perry
    restart: on-failure
    ports:
      - 8081:8081
    expose:
      - 8081
    env_file: docker-compose.env
